### ISSUE TITLE
'MXNetParser' object has no attribute 'weight_data'

### ISSUE THREAD

**Issue by amazingzby** [Microsoft/MMdnn#309]
Platform (ubuntu 17.04):

Python version:3.6

Source framework with version (lTensorflow 1.2.0 with CPU):

Traceback (most recent call last):
  File "/home/zby/work/software/anaconda3/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.1.4', 'console_scripts', 'mmtoir')()
  File "/home/zby/work/software/anaconda3/lib/python3.6/site-packages/mmdnn-0.1.4-py3.6.egg/mmdnn/conversion/_script/convertToIR.py", line 180, in _main
    ret = _convert(args)
  File "/home/zby/work/software/anaconda3/lib/python3.6/site-packages/mmdnn-0.1.4-py3.6.egg/mmdnn/conversion/_script/convertToIR.py", line 98, in _convert
    parser.run(args.dstPath)
  File "/home/zby/work/software/anaconda3/lib/python3.6/site-packages/mmdnn-0.1.4-py3.6.egg/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/zby/work/software/anaconda3/lib/python3.6/site-packages/mmdnn-0.1.4-py3.6.egg/mmdnn/conversion/mxnet/mxnet_parser.py", line 262, in gen_IR
    func(current_node)
  File "/home/zby/work/software/anaconda3/lib/python3.6/site-packages/mmdnn-0.1.4-py3.6.egg/mmdnn/conversion/mxnet/mxnet_parser.py", line 752, in rename_LeakyReLU
    self.set_weight(source_node.name, "gamma", self.weight_data.get(source_node.name + "_gamma").asnumpy())
AttributeError: 'MXNetParser' object has no attribute 'weight_data'

**Comment by namizzz** [comment]
Hi @amazingzby , if 'MXNetParser' object has no attribute 'weight_data', you can check if you feed the **".params"** file to the mmdnn. Thanks!
