### ISSUE TITLE
TF -> Caffe. KeyError: 'worker_0/resnet_v2_50/conv1/weights' for resnet_v2_50

### ISSUE THREAD

**Issue by Shadowspyes** [Microsoft/MMdnn#427]
**Platform (like ubuntu 16.04/win10):** 
win10

**Python version:**
3.6

**Source framework with version (like Tensorflow 1.4.1 with GPU):**
tried with tf 1.8.0 and 1.10 (newest)

**Destination framework with version (like CNTK 2.3 with GPU):**
Caffe

**Pre-trained model path (webpath or webdisk path):**
resnet_v2_50

**Running scripts:**
mmconvert -sf tensorflow -in model-0.ckpt.meta -iw model-0.ckpt.index --dstNodeName worker_0/resnet_v2_50/logits/BiasAdd -df caffe -om tf_resnet

I get the KeyError: 'worker_0/resnet_v2_50/conv1/weights', but when I check the layers of the model, the
one in the keyerror is present:

worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/shape
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/min
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/max
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/RandomUniform
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/sub
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform/mul
worker_0/resnet_v2_50/conv1/weights/Initializer/random_uniform
worker_0/resnet_v2_50/conv1/weights
worker_0/resnet_v2_50/conv1/weights/Assign
worker_0/resnet_v2_50/conv1/weights/read

3rd from the bottom.

It should also be noted that I tried running mmconvert -sf tensorflow -in model-0.ckpt.meta -iw model-0.ckpt --dstNodeName worker_0/resnet_v2_50/logits/BiasAdd -df caffe -om tf_resnet
^^removed .index from -iw file^^
but this results in "AttributeError: 'NoneType' object has no attribute 'name'" for     self.set_weight(source_node.name, 'mean', self.ckpt_data[mean.name]).

Any help would be greatly appreciated!

**Comment by Shadowspyes** [comment]
@namizzz here are the files:

https://ufile.io/p5jb5

**Comment by namizzz** [comment]
Hi @Shadowspyes , I have checked your model files. It's caused by name of the moving_mean and moving_variance. You can fix this in [tensorflow_parser.py ](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/tensorflow_parser.py#L700) . Add:
```python
node_name = '/'.join(source_node.name.split('/')[:-1]) + '/'
```
to get your node name (eg. worker_0/resnet_v2_50/block2/unit_1/bottleneck_v2/preact/)

Then you can comment Line 703 and 704. Add:
```python
self.set_weight(source_node.name, 'mean', self.ckpt_data[node_name + 'moving_mean'])
self.set_weight(source_node.name, 'var', self.ckpt_data[node_name + 'moving_variance'])

```
Thanks!

**Comment by Shadowspyes** [comment]
@namizzz Thank you for your assistance!
