### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by krishnavishalv** [Microsoft/MMdnn#164]
Platform (like ubuntu 16.04/win10):

Python version: Python 3.6.4 |Anaconda custom (64-bit)

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.4.1 with GPU

Destination framework with version (like CNTK 2.3 with GPU): Pytorch 0.4.0

Pre-trained model path (webpath or webdisk path):

Running scripts:

I ran this command to convert my tensorflow model to pytorch model. 

```
mmconvert -sf tensorflow -in flat-6200.meta -iw flat-6200 --dstNode AvgPool_1/AvgPool -df pytorch -om tf_to_pytorch_orbmodel.pth
```

This is the error trace I got. 

```
/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Parse file [flat-6200.meta] with binary format successfully.
Tensorflow model file [flat-6200.meta] loaded successfully.
Tensorflow checkpoint file [flat-6200] loaded successfully. [58] variables loaded.
Tensorflow has not supported operator [NoOp] with name [Layer_1/BatchNorm/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_1/BatchNorm/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_1/BatchNorm/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [Layer_1/BatchNorm/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [Layer_1/dropout/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_1/dropout/cond/dropout/Shape/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/BatchNorm/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/BatchNorm/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/BatchNorm/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/BatchNorm/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/dropout/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_2/dropout/cond/dropout/Shape/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/BatchNorm/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/BatchNorm/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/BatchNorm/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/BatchNorm/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/dropout/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_3/dropout/cond/dropout/Shape/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/BatchNorm/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/BatchNorm/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/BatchNorm/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/BatchNorm/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/dropout/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_4/dropout/cond/dropout/Shape/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/BatchNorm/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/BatchNorm/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/BatchNorm/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/BatchNorm/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/dropout/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [Layer_5/dropout/cond/dropout/Shape/Switch:1].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_1/dropout/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_2/dropout/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_3/dropout/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_4/dropout/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/Switch].
Tensorflow has not supported operator [Switch] with name [Layer_5/dropout/cond/Switch].
Tensorflow has not supported operator [Shape] with name [Layer_1/dropout/cond/dropout/Shape].
Tensorflow has not supported operator [Shape] with name [Layer_2/dropout/cond/dropout/Shape].
Tensorflow has not supported operator [Shape] with name [Layer_3/dropout/cond/dropout/Shape].
Tensorflow has not supported operator [Shape] with name [Layer_4/dropout/cond/dropout/Shape].
Tensorflow has not supported operator [Shape] with name [Layer_5/dropout/cond/dropout/Shape].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [Layer_1/BatchNorm/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [Layer_2/BatchNorm/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [Layer_3/BatchNorm/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [Layer_4/BatchNorm/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [Layer_5/BatchNorm/cond/FusedBatchNorm_1/Switch_4].
Traceback (most recent call last):
  File "/home/vvv/anaconda3/envs/tensor/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 90, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 90, in _convert
    parser.run(args.dstPath)
  File "/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 281, in gen_IR
    func(current_node)
  File "/home/vvv/anaconda3/envs/tensor/lib/python3.6/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 589, in rename_FusedBatchNorm
    self.set_weight(source_node.name, 'scale', self.ckpt_data[scale.name])
AttributeError: 'NoneType' object has no attribute 'name'

```
I don't know what the long errors mean. Can someone here help me ? 
I will upload trained model files if needed.

**Comment by JiahaoYao** [comment]
Hi krishnavishalv, 
     Would you like to share your trained model files? Or just simply give me a dropbox link?

**Comment by krishnavishalv** [comment]
@JiahaoYao I have sent google drive link to the email mentioned on your GitHub profile.

**Comment by JiahaoYao** [comment]
@krishnavishalv All right! I have already received your pre-trained model. 
I print out the layer name of your model as follows:

`Optimizer/Layer_4/Conv/Filter/Adam_1
Layer_5/BatchNorm/moving_variance
Layer_1/Conv/Filter
Layer_5/BatchNorm/moving_mean
Optimizer/Layer_2/Conv/Bias/Adam_1
Optimizer/Layer_4/BatchNorm/beta/Adam_1
Optimizer/Layer_4/BatchNorm/beta/Adam
Layer_2/BatchNorm/moving_variance
Optimizer/Layer_5/Conv/Bias/Adam_1
Layer_2/BatchNorm/beta
Layer_4/Conv/Filter
Optimizer/Layer_5/BatchNorm/beta/Adam
Layer_1/Conv/Bias
Optimizer/Layer_1/BatchNorm/beta/Adam
Layer_1/BatchNorm/beta
Layer_5/BatchNorm/beta
Input/global_step
Layer_3/Conv/Bias
Layer_4/BatchNorm/beta
Optimizer/Layer_3/Conv/Filter/Adam
Optimizer/Layer_4/Conv/Filter/Adam
Optimizer/Layer_1/Conv/Filter/Adam_1
Layer_3/BatchNorm/beta
Optimizer/Layer_3/Conv/Bias/Adam_1
Optimizer/Layer_4/Conv/Bias/Adam
Optimizer/Layer_1/BatchNorm/beta/Adam_1
Optimizer/Layer_5/BatchNorm/beta/Adam_1
Optimizer/Layer_5/Conv/Filter/Adam
Layer_3/BatchNorm/moving_mean
Layer_2/Conv/Filter
Optimizer/Layer_5/Conv/Bias/Adam
Optimizer/Layer_4/Conv/Bias/Adam_1
Optimizer/Layer_3/Conv/Bias/Adam
Optimizer/Layer_3/BatchNorm/beta/Adam
Optimizer/Layer_2/BatchNorm/beta/Adam_1
Optimizer/Layer_1/Conv/Bias/Adam
Optimizer/Layer_2/Conv/Filter/Adam_1
Layer_1/BatchNorm/moving_variance
Layer_3/BatchNorm/moving_variance
Optimizer/Layer_1/Conv/Bias/Adam_1
Layer_5/Conv/Bias
Optimizer/Layer_3/Conv/Filter/Adam_1
Layer_4/Conv/Bias
Layer_3/Conv/Filter
Layer_4/BatchNorm/moving_variance
Optimizer/beta2_power
Optimizer/Layer_2/BatchNorm/beta/Adam
Layer_1/BatchNorm/moving_mean
Optimizer/Layer_2/Conv/Filter/Adam
Layer_2/BatchNorm/moving_mean
Layer_5/Conv/Filter
Optimizer/Layer_1/Conv/Filter/Adam
Optimizer/Layer_3/BatchNorm/beta/Adam_1
Optimizer/Layer_5/Conv/Filter/Adam_1
Layer_4/BatchNorm/moving_mean
Optimizer/beta1_power
Layer_2/Conv/Bias
Optimizer/Layer_2/Conv/Bias/Adam`

So, if I understand correctly, you were using Adam. You can filter out what you need using the var list when creating the saver, and omit the Adam variables for MMdnn does not take into consideration the trainable Adam variables. Hope I figure it out.

**Comment by JiahaoYao** [comment]
I do not know why. I wonder if someone else could help to figure it out.

**Comment by krishnavishalv** [comment]
@kitstar can you help me  ?

**Comment by Pfaeff** [comment]
I am having the same issue when trying to convert a resnetv2 from tensorflow.

**Comment by kitstar** [comment]
Hi @krishnavishalv and @Pfaeff , @JiahaoYao is working on inception_resnet models. We will ping you asap. Thanks.

**Comment by namizzz** [comment]
Hi @krishnavishalv  and @Pfaeff ,We have implemented the inception_resnet part.Try the newest code,Thanks!

**Comment by kevinjunwei** [comment]
@krishvishal have you resolved the problom, when i tired to convert tensorflow squeezeNet (with batch normalization layer), this question still confused me. can you give me some advices?
Parse file [squeezeNet_ori-occ-cls-100-1.85684-50001.meta] with binary format successfully.
Tensorflow model file [squeezeNet_ori-occ-cls-100-1.85684-50001.meta] loaded successfully.
Tensorflow checkpoint file [squeezeNet_ori-occ-cls-100-1.85684-50001] loaded successfully. [89] variables loaded.
Tensorflow has not supported operator [NoOp] with name [batch_normalization/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_1/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_1/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_1/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_1/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_2/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_2/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_2/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_2/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_3/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_3/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_3/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_3/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_4/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_4/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_4/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_4/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_5/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_5/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_5/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_5/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_6/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_6/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_6/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_6/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_7/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_7/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_7/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_7/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_8/cond/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_8/cond/FusedBatchNorm/Switch:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_8/cond/FusedBatchNorm/Switch_1:1].
Tensorflow has not supported operator [NoOp] with name [batch_normalization_8/cond/FusedBatchNorm/Switch_2:1].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/Switch].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_1/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_2/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_3/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_4/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_5/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_6/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_7/cond/FusedBatchNorm_1/Switch_4].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm_1/Switch_1].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm_1/Switch_2].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm_1/Switch_3].
Tensorflow has not supported operator [Switch] with name [batch_normalization_8/cond/FusedBatchNorm_1/Switch_4].
