### ISSUE TITLE
resnet form caffe to IR

### ISSUE THREAD

**Issue by DRACOyu** [Microsoft/MMdnn#340]
Platform (like ubuntu 16.04/win10):
ubuntu 16.04
Python version:
python2.7
Source framework with version (like Tensorflow 1.4.1 with GPU):
Tensorflow1.2
Destination framework with version (like CNTK 2.3 with GPU):
IR
Pre-trained model path (webpath or webdisk path):
RESNET152
Running scripts:
mmtoir -f caffe -n resnet152-deploy.prototxt -w resnet152.caffemodel -o caffe_resnet_IR（注意修改下载的文件名和命令中的一致），若成功会产生caffe_resnet_IR.json（709KB），caffe_resnet_IR.pb（67KB）和caffe_resnet_IR.npy（347MB）三个文件
Traceback (most recent call last):
  File "anaconda2/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmtoir')()
  File "/caffe_to_tensorflow/MMdnn-master/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "caffe_to_tensorflow/MMdnn-master/mmdnn/conversion/_script/convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by namizzz** [comment]
Hi @DRACOyu , thanks for your issue. We have fixed it, try the newest code!
