### ISSUE TITLE
TypeError: upsample_bilinear2d() got an unexpected keyword argument 'align_corners' (occurred when translating upsample_bilinear2d)

### ISSUE THREAD

**Issue by Deocacaff** [Microsoft/MMdnn#549]
Platform (like ubuntu 16.04/win10):
ubuntu 16.04/linux
Python version:
Python 3.5.6 
Source framework with version (like Tensorflow 1.4.1 with GPU):
Pytorch:0.4.0
Caffe:1.0.0
Running scripts:
mmtoir -f pytorch -d my_model2IR --inputShape 3,400,400 -n my_model.pth

My model use torch.nn.functional.upsample(x, out_size[2:], mode='bilinear') in pytorch 0.4.0
After I saved my whole model to "pth" file, I used mmdnn(mmtoir command) to transform IR file. I met the error message

File "/home/miniconda3/envs/mmdnn/bin/mmtoir", line 11, in <module> sys.exit(_main())
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main ret = _convert(args)
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert parser = PytorchParser(args.network, inputshape[0])
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 88, in __init__ self.pytorch_graph.build(self.input_shape)
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 124, in build trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _optimize_graph graph = torch._C._jit_pass_onnx(graph, aten)
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/torch/onnx/__init__.py", line 40, in _run_symbolic_function   return utils._run_symbolic_function(*args, **kwargs)
File "/home/miniconda3/envs/mmdnn/lib/python3.5/site-packages/torch/onnx/utils.py", line 368, in _run_symbolic_function return fn(g, *inputs, **attrs)
TypeError: upsample_bilinear2d() got an unexpected keyword argument 'align_corners' (occurred when translating upsample_bilinear2d)

**Comment by Kaidy-Boom** [comment]
A naive but workable way, edit the source code. Pop the item with key "align_corners" in the arguments dict() before passing it into onnx ops.

**Comment by mshmoon** [comment]
> dit the source

Hi ,I meet the sample problem.Can you tell me some details about how to modify the code? Thank you

**Comment by mshmoon** [comment]
> A naive but workable way, edit the source code. Pop the item with key "align_corners" in the arguments dict() before passing it into onnx ops.

hi.I meet the sample problem.Can you tell me some details about how to modify the code? Thank you
@mshmoon

**Comment by mshmoon** [comment]
> A naive but workable way, edit the source code. Pop the item with key "align_corners" in the arguments dict() before passing it into onnx ops.
hi
