### ISSUE TITLE
How to use the convert pytorch model to fine tune new dataset

### ISSUE THREAD

**Issue by queenie88** [Microsoft/MMdnn#487]
Platform (like ubuntu 16.04/win10): unbuntu 14

Python version: 3.6 

Source framework with version (like Tensorflow 1.4.1 with GPU):caffe 

Destination framework with version (like CNTK 2.3 with GPU): pytorch

Pre-trained model path (webpath or webdisk path):

Running scripts:
I have the converted pre-train model, I want to use it to fine-tune the other dataset.
I want to know how to get the last layer, I can not change the class number. I want to know how I can train with the converted pre-train model.
    MainModel = imp.load_source('MainModel',"./convertion_inception21k/Inception21k.py")
    model_ft = torch.load(model_path)
    num_ftrs = model_ft.Linear.in_features
results:
  File "/home/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'KitModel' object has no attribute 'Linear'

**Comment by rainLiuplus** [comment]
Hi @queenie88 , it seems that ./convertion_inception21k/Inception21k.py is the converted pytorch file and you can open it to see the network structure, which will help you fine-tune the model.  Thanks.
