### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'height'

### ISSUE THREAD

**Issue by danzigjabalpur** [Microsoft/MMdnn#323]
Platform (like ubuntu 16.04 - virtualbox):

Python version: 2.7

Source framework with version (like Tensorflow 1.7.0 no GPU):

Caffe: https://github.com/rbgirshick/fast-rcnn

Pre-trained model path: 
https://github.com/liuziwei7/fashion-detection

Running scripts:

> Traceback (most recent call last):
  File "/home/danzig/.local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 9, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", args.inputShape, phase = args.caffePhase)
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/transformer.py", line 318, in __init__
    graph = GraphBuilder(def_path, self.input_shape, self.is_train_proto, phase).build()
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 450, in build
    graph.compute_output_shapes(self.model)
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 269, in compute_output_shapes
    node.output_shape = TensorShape(*NodeKind.compute_output_shape(node))
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/graph.py", line 129, in compute_output_shape
    return LAYER_DESCRIPTORS[node.kind](node)
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/shape.py", line 99, in shape_convolution
    return get_strided_kernel_output_shape(node, math.floor)
  File "/home/danzig/.local/lib/python2.7/site-packages/mmdnn/conversion/caffe/shape.py", line 26, in get_strided_kernel_output_shape
    o_h, o_w = get_filter_output_shape(input_shape.height, input_shape.width,
AttributeError: 'tuple' object has no attribute 'height'

Im not familiar with caffe and R-CNN so im not sure which command to use so i tested with these two:

> mmconvert -sf caffe -in fashion_detector.prototxt -iw fashion_detector.caffemodel -df tensorflow -om ./caffe_fcn32s

> python2 -m mmdnn.conversion._script.convertToIR -f caffe -d kit_imagenet -n fashion_detector.prototxt -w fashion_detector.caffemodel

**Comment by namizzz** [comment]
Hi @danzigjabalpur , Please provide your 'prototxt' file.Thanks
