### ISSUE TITLE
Unable to convert MobiletNet_v1 from Pytorch to Tensorflow

### ISSUE THREAD

**Issue by rakelkar** [Microsoft/MMdnn#527]
I am attempting to convert a pytorch model (saved during training using torch.save) to tensorflow. The model was trained using: https://github.com/rakelkar/pytorch-mobilenet

I am new to pytorch so please excuse potential dumbness.. I see that the conversion fails with:
AttributeError: 'dict' object has no attribute 'state_dict'

at mmdnn/conversion/pytorch/pytorch_parser.py:
'''
        # cpu: https://github.com/pytorch/pytorch/issues/5286
        try:
            model = torch.load(model_file_name)
        except:
            model = torch.load(model_file_name, map_location='cpu')

        self.weight_loaded = True

        # Build network graph
        print(model)
        self.pytorch_graph = PytorchGraph(model)
        self.input_shape = tuple([1] + input_shape)
        self.pytorch_graph.build(self.input_shape)

       ## fails here!!
       ## fails here!!
       ## fails here!!
        self.state_dict = self.pytorch_graph.state_dict
       ## fails here!!

        self.shape_dict = self.pytorch_graph.shape_dict
'''

per the pytorch docs - the right way to load the model is:
'''
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))
'''

So my question is - should I be adding my model class to the repo somehow?

Platform (like ubuntu 16.04/win10): 
ubuntu 16.04

Python version: 
3.5.6

Source framework with version (like Tensorflow 1.4.1 with GPU):
Pytorch 1.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU):
Tensorflow

**$ mmtoir -f pytorch -d mobilenet_v1 --inputShape 3,224,224 -n model_best.pth.tar** 
Traceback (most recent call last):
  File "/home/rakelkar/anaconda3/envs/fastai/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _conv$rt
    parser = PytorchParser(args.network, inputshape[0])
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 82, in __$nit__
    self.pytorch_graph = PytorchGraph(model)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 59, in __i$it__
    self.state_dict = _unique_state_dict(self.model)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py", line 200, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'dict' object has no attribute 'state_dict'

**Comment by rakelkar** [comment]
Hmm - maybe the issue is to do with how the checkpoint is saved (state_dict appears to be nested)
{
            'epoch': epoch + 1,
            'arch': args.arch,
            'state_dict': model.state_dict(),
            'best_prec1': best_prec1,
            'optimizer' : optimizer.state_dict(),
        }

**Comment by rakelkar** [comment]
Fails even after I extracted the state_dict and also accounted for DataParallel...
```
import torch
import mobilenet

model = mobilenet.Net()
checkpoint = torch.load("model_best.pth.tar")
state_dict = checkpoint['state_dict']
for k in list(state_dict.keys()):
  state_dict[k[7::]] = state_dict.pop(k)
model.load_state_dict(state_dict)
torch.save(model.state_dict(), "amazing.pth")
```

Still fails with:
Traceback (most recent call last):
  File "/home/rakelkar/anaconda3/envs/fastai/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 82, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 59, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py", line 200, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

**Comment by rainLiuplus** [comment]
Seems it is still not a model file. Please refer this https://stackoverflow.com/questions/49941426/attributeerror-collections-ordereddict-object-has-no-attribute-eval

**Comment by rakelkar** [comment]
I saved the pickled model per your suggestion - then I had to hack around to make model class available for unpickling... I hacked it by copying my model file into the mmdnn/conversion/pytorch and using that to pickle:
```
model = mmdnn.conversion.pytorch.mobilenet.Net()
model.load_state_dict(state_dict)
torch.save(model, "mnet.pth")
```
Not sure what the correct (non-hacky) way to get this unpickle correctly...

Anyhow, conversion then ran and failed with: incompatible function arguments
```
    (14): AvgPool2d(kernel_size=7, stride=7, padding=0)                                                                   [1027/1929]
  )
  (fc): Linear(in_features=1024, out_features=1000, bias=True)
)
Traceback (most recent call last):
  File "/home/rakelkar/anaconda3/envs/fastai/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _conve
rt
    parser = PytorchParser(args.network, inputshape[0])
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 85, in __i
nit__
    self.pytorch_graph.build(self.input_shape)
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 124, in bui
ld
    trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
  File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _opt
imize_graph
    graph = torch._C._jit_pass_onnx(graph, aten)
TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph

Invoked with: graph(%0 : Float(1, 3, 224, 224)
      %1 : Float(32, 3, 3, 3)
      %2 : Float(32)
      %3 : Float(32)
```

**Comment by rainLiuplus** [comment]
Could you please provide your model for us to debug? Thanks!

**Comment by rakelkar** [comment]
Basically this:
```
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()

        def conv_bn(inp, oup, stride):
            return nn.Sequential(
                nn.Conv2d(inp, oup, 3, stride, 1, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True)
            )

        def conv_dw(inp, oup, stride):
            return nn.Sequential(
                nn.Conv2d(inp, inp, 3, stride, 1, groups=inp, bias=False),
                nn.BatchNorm2d(inp),
                nn.ReLU(inplace=True),
    
                nn.Conv2d(inp, oup, 1, 1, 0, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True),
            )

        self.model = nn.Sequential(
            conv_bn(  3,  32, 2), 
            conv_dw( 32,  64, 1),
            conv_dw( 64, 128, 2),
            conv_dw(128, 128, 1),
            conv_dw(128, 256, 2),
            conv_dw(256, 256, 1),
            conv_dw(256, 512, 2),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 1024, 2),
            conv_dw(1024, 1024, 1),
            nn.AvgPool2d(7),
        )
        self.fc = nn.Linear(1024, 1000)

    def forward(self, x):
        x = self.model(x)
        x = x.view(-1, 1024)
        x = self.fc(x)
        return x
```

**Comment by linmajia** [comment]
@rakelkar , have you tried MMdnn to convert your new ONNX model to TensorFlow's format?

**Comment by oyrq** [comment]
> I saved the pickled model per your suggestion - then I had to hack around to make model class available for unpickling... I hacked it by copying my model file into the mmdnn/conversion/pytorch and using that to pickle:
> 
> ```
> model = mmdnn.conversion.pytorch.mobilenet.Net()
> model.load_state_dict(state_dict)
> torch.save(model, "mnet.pth")
> ```
> Not sure what the correct (non-hacky) way to get this unpickle correctly...
> 
> Anyhow, conversion then ran and failed with: incompatible function arguments
> 
> ```
>     (14): AvgPool2d(kernel_size=7, stride=7, padding=0)                                                                   [1027/1929]
>   )
>   (fc): Linear(in_features=1024, out_features=1000, bias=True)
> )
> Traceback (most recent call last):
>   File "/home/rakelkar/anaconda3/envs/fastai/bin/mmtoir", line 11, in <module>
>     sys.exit(_main())
>   File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
>     ret = _convert(args)
>   File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _conve
> rt
>     parser = PytorchParser(args.network, inputshape[0])
>   File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 85, in __i
> nit__
>     self.pytorch_graph.build(self.input_shape)
>   File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 124, in bui
> ld
>     trace.set_graph(PytorchGraph._optimize_graph(trace.graph(), False))
>   File "/home/rakelkar/anaconda3/envs/fastai/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 74, in _opt
> imize_graph
>     graph = torch._C._jit_pass_onnx(graph, aten)
> TypeError: _jit_pass_onnx(): incompatible function arguments. The following argument types are supported:
>     1. (arg0: torch::jit::Graph, arg1: torch._C._onnx.OperatorExportTypes) -> torch::jit::Graph
> 
> Invoked with: graph(%0 : Float(1, 3, 224, 224)
>       %1 : Float(32, 3, 3, 3)
>       %2 : Float(32)
>       %3 : Float(32)
> ```
Hi,I have the same problem,Has your problem been solved ? Thanks !
