### ISSUE TITLE
AttributeError: 'Conv2d' object has no attribute 'padding_mode'

### ISSUE THREAD

**Issue by soham24** [microsoft/MMdnn#656]
Platform (like ubuntu 16.04/win10):  ubuntu 16.04

Python version: 3.5

Source framework with version (like Tensorflow 1.4.1 with GPU): pytorch 0.4

Destination framework with version (like CNTK 2.3 with GPU): caffe

Pre-trained model path (webpath or webdisk path): https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe

Running scripts:
trying to convert pth to IR
