### ISSUE TITLE
AttributeError: module 'keras.applications.mobilenet' has no attribute 'relu6'

### ISSUE THREAD

**Issue by pkl728** [Microsoft/MMdnn#268]
Platform (like ubuntu 16.04/win10): macOS 10.13.5

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.8

Destination framework with version (like CNTK 2.3 with GPU): toIR

Pre-trained model path (webpath or webdisk path): ./version0056.h5

Running scripts:
python -m mmdnn.conversion._script.convertToIR -f keras -d connect4_mobilenet -w version0056.h5

I have created a keras model using the example found here: https://github.com/AppliedDataSciencePartners/DeepReinforcementLearning

My ultimate goal is to try and import this into coreML to test with an iOS app. When I first try to convert to IR in order to convert to coreML I get the following issue:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/anaconda3/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 39, in _convert
    parser = Keras2Parser(model)
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 94, in __init__
    'relu6': _keras.applications.mobilenet.relu6,
AttributeError: module 'keras.applications.mobilenet' has no attribute 'relu6'
```

Seems like perhaps relu6 is not supported or something like that? Sorry new to this and trying to teach myself how this all fits together!

**Comment by JiahaoYao** [comment]
Hi @pkl728, Do you use the latest MMdnn?

**Comment by nkalupahana** [comment]
I just recently installed the latest mmdnn (I think? I installed it today via pip; how would I check the version?), and am running into the same problem. Does anybody know what's going on?

**Comment by JiahaoYao** [comment]
So, you pip install like this?
```bash
pip install -U git+https://github.com/Microsoft/MMdnn.git@master
```

**Comment by nkalupahana** [comment]
I actually ran `pip install mmdnn` -- so that worked! Thank you so much! @pkl728 The above command should work

**Comment by pkl728** [comment]
Excellent!! I will give it a try

**Comment by JiahaoYao** [comment]
Hi @pkl728, this problem has something to do with `emit_Tanh`. I have created a pull request to solve this problem. Hoping that it will be helpful to you.

**Comment by pkl728** [comment]
Thanks @JiahaoYao! Tracked it down to an assertion at the top of the function... was that there because that function is not fully vetted?

**Comment by pkl728** [comment]
Now the final (I think) issue I'm running into is that it doesn't seem like CoreML can handle this kind of model... I get the following:

python -m mmdnn.conversion._script.IRToModel -f coreml -in connect4_mobilenet.pb -iw connect4_mobilenet.npy -o connect4.mlmodel
WARNING:root:Keras version 2.2.0 detected. Last version known to be fully compatible of Keras is 2.1.3 .
WARNING:root:TensorFlow version 1.8.0 detected. Last version known to be fully compatible is 1.5.0 .
Parse file [connect4_mobilenet.pb] with binary format successfully.
CoreML Model Input Layer: [main_input] Array({7,2,6})
CoreML Model Output Layer: [policy_head] Array({42})
CoreML Model Output Layer: [value_head_activation] Array({1})
Converting layer main_input(DataInput)
Converting layer conv2d_66(Conv)
Converting layer batch_normalization_66(BatchNorm)
Converting layer leaky_re_lu_71(LeakyRelu)
Converting layer conv2d_67(Conv)
Converting layer batch_normalization_67(BatchNorm)
Converting layer leaky_re_lu_72(LeakyRelu)
Converting layer conv2d_68(Conv)
Converting layer batch_normalization_68(BatchNorm)
Converting layer add_26(Add)
Converting layer leaky_re_lu_73(LeakyRelu)
Converting layer conv2d_69(Conv)
Converting layer batch_normalization_69(BatchNorm)
Converting layer leaky_re_lu_74(LeakyRelu)
Converting layer conv2d_70(Conv)
Converting layer batch_normalization_70(BatchNorm)
Converting layer add_27(Add)
Converting layer leaky_re_lu_75(LeakyRelu)
Converting layer conv2d_71(Conv)
Converting layer batch_normalization_71(BatchNorm)
Converting layer leaky_re_lu_76(LeakyRelu)
Converting layer conv2d_72(Conv)
Converting layer batch_normalization_72(BatchNorm)
Converting layer add_28(Add)
Converting layer leaky_re_lu_77(LeakyRelu)
Converting layer conv2d_73(Conv)
Converting layer batch_normalization_73(BatchNorm)
Converting layer leaky_re_lu_78(LeakyRelu)
Converting layer conv2d_74(Conv)
Converting layer batch_normalization_74(BatchNorm)
Converting layer add_29(Add)
Converting layer leaky_re_lu_79(LeakyRelu)
Converting layer conv2d_75(Conv)
Converting layer batch_normalization_75(BatchNorm)
Converting layer leaky_re_lu_80(LeakyRelu)
Converting layer conv2d_76(Conv)
Converting layer batch_normalization_76(BatchNorm)
Converting layer add_30(Add)
Converting layer leaky_re_lu_81(LeakyRelu)
Converting layer conv2d_77(Conv)
Converting layer conv2d_78(Conv)
Converting layer batch_normalization_77(BatchNorm)
Converting layer batch_normalization_78(BatchNorm)
Converting layer leaky_re_lu_82(LeakyRelu)
Converting layer leaky_re_lu_84(LeakyRelu)
Converting layer flatten_11(Flatten)
Converting layer flatten_12(Flatten)
Converting layer dense_6(FullyConnected)
Converting layer policy_head(FullyConnected)
Converting layer leaky_re_lu_83(LeakyRelu)
Converting layer value_head(FullyConnected)
Converting layer value_head_activation(Tanh)
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToModel.py", line 129, in <module>
    _main()
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToModel.py", line 124, in _main
    ret = _convert(args)
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToModel.py", line 36, in _convert
    predicted_feature_name = args.predictedFeatureName)
  File "/anaconda3/lib/python3.6/site-packages/mmdnn/conversion/coreml/coreml_emitter.py", line 139, in gen_model
    image_scale=image_scale)
  File "/anaconda3/lib/python3.6/site-packages/coremltools/models/neural_network.py", line 2556, in set_pre_processing_parameters
    raise ValueError("Channel Value %d not supported for image inputs" % channels)
ValueError: Channel Value 7 not supported for image inputs

Any ideas??

**Comment by pkl728** [comment]
So in doing some more research, this looks like a result of needing to make use of the 'add_custom_layers' functionality of CoreML as by default they only support 1 or 3 layers. I don't see the 'mmdnn.conversion._script.IRToModel' script making use of that parameter anywhere... Is this type of model conversion on the roadmap for the MMdnn team?

**Comment by namizzz** [comment]
Hi @pkl728 
Here is the code of [CoremlEmitter](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/coreml/coreml_emitter.py).
Because "CoreML Model Input Layer: [main_input] Array({7,2,6})"  , "ValueError: Channel Value 7 not supported for image inputs" , maybe you can remove this part 
```code
self.builder.set_pre_processing_parameters(
            image_input_names=[input_features[0][0]],
            #image_input_names,
            is_bgr=is_bgr,
            red_bias=red_bias,
            green_bias=green_bias,
            blue_bias=blue_bias,
            gray_bias=gray_bias,
            image_scale=image_scale)
```
to see if it work? Thanks!

**Comment by aaronduino** [comment]
I have this error on the latest mmdnn, except it's with `keras_applications` instead of `keras.applications`.

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 105, in __init__
    'relu6': _keras.applications.mobilenet.relu6,
AttributeError: module 'keras.applications.mobilenet' has no attribute 'relu6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/bin/mmconvert", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "/home/username/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/username/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/home/username/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 115, in __init__
    'relu6': mobilenet.relu6,
AttributeError: module 'keras_applications.mobilenet' has no attribute 'relu6'

```

**Comment by aaronduino** [comment]
Related: https://github.com/keras-team/keras/issues/7431

**Comment by namizzz** [comment]
Hi @aaronduino  Fixed! Thanks!

**Comment by pageedward** [comment]
@aaronduino have u fix the problom convert keras mobilenet to tensorflow or caffe ,i have problem is TensorflowEmitter has not supported operator [Model].
mobilenetv2_1.00_128, how to fix it, thank u

**Comment by schliffen** [comment]
To convert you model to coreml (.mlmodel) with tensorflow 1.9 and keras 2.2.0 this is what I did and it worked completely:

from tensorflow.python.keras.models import load_model
from keras.applications.mobilenet import MobileNet
from tensorflow.python.keras.applications import mobilenet
from tensorflow.python.keras.utils.generic_utils import CustomObjectScope
with CustomObjectScope({'relu6': mobilenet.relu6,'DepthwiseConv2D': mobilenet.DepthwiseConv2D}):
    loaded_model.load_weights('model_.h5')

for complete model you should import your model separately, e.g. using model_from_json
coreml_model = coremltools.converters.keras.convert(loaded_model)
coreml_model.save('coreml_model')

**Comment by shreshtha-pankaj** [comment]
Latest fix:

pip3.7 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl
