### ISSUE TITLE
Caffe->Pytorch load model eval() failed

### ISSUE THREAD

**Issue by wuziheng** [Microsoft/MMdnn#577]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: python 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): caffe GPU

Destination framework with version (like CNTK 2.3 with GPU): pytorch 1.0.0

Pre-trained model path (webpath or webdisk path):  resnet50 with private dataset

Running scripts:

  File "train.py", line 44, in __init__
    the_model.eval()
  File "/home/wuziheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1000, in eval
    return self.train(False)
  File "/home/wuziheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 988, in train
    for module in self.children():
  File "/home/wuziheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 888, in children
    for name, module in self.named_children():
  File "/home/wuziheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 906, in named_children
    for name, module in self._modules.items():
  File "/home/wuziheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'KitModel' object has no attribute '_modules'

according to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md ,I transfer a caffemodel to pytorch model, which use python2, and furthur we need use this model in python3.6 pytorch, i have already fixed torch.load with encoding, and faided at the_model.eval() step. help!

**Comment by rainLiuplus** [comment]
Hi @wuziheng , Maybe you can downgrade pytorch to 0.4.0 to have a try. Thanks!

**Comment by SebastienEske** [comment]
Hello,
First python2 is (or is about to be) deprecated so I really would not advise to use it anymore.

Regarding your issue, the stack trace says that during your call to the `eval()` function, pytorch is unable to load the children modules of your network because it is missing the attribute `_modules`. So you should look in the python file generated by MMdnn. Make sure that the definition and initialization of the KitModel class inherits from the module class:
```
class KitModel(nn.Module):
    def __init__(self, weight_file):
        super(KitModel, self).__init__()
```
Both of the above should solve it. If not try a more simple model such as VGG and see if it works.

**Comment by SebastienEske** [comment]
Side note: MMdnn and caffe work fine with python3. You may need to recompile caffe for python `make pycaffe`.
