### ISSUE TITLE
Places365 Caffe to pytorc. Error when using the generated files

### ISSUE THREAD

**Issue by dhorka** [Microsoft/MMdnn#611]
Platform (like ubuntu 16.04/win10): Ubuntu 16

Python version: 2.7

Source framework with version (like Tensorflow 1.4.1 with GPU): Caffe

Destination framework with version (like CNTK 2.3 with GPU): Pytorch 0.4.1

Pre-trained model path (webpath or webdisk path): https://github.com/CSAILVision/places365 In specific I am trying to convert VGG16-hybrid1365 and ResNet152-hybrid1365

Running scripts: mmconvert --srcFramework caffe --inputWeight vgg16_hybrid1365.caffemodel --inputNetwork deploy_vgg16_hybrid1365.prototxt --dstFramework pytorch -om vgg16places.pth

Hi,

As I described above, I am trying to convert places caffe pre-trained models to pytorch. The convertion procedure finish without error, but, When I want to use it I have troubles. These files are generated:

- vgg16places.pth

- vgg16places.py

The code that I am using in order to use the converted files is : 

> >>> import vgg16places as vgg 
> >>> a = vgg.KitModel('vgg16places.pth') 
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "vgg16places.py", line 26, in __init__
>     __weights_dict = load_weights(weight_file)
>   File "vgg16places.py", line 16, in load_weights
>     weights_dict = np.load(weight_file, encoding='bytes').item()
> AttributeError: 'long' object has no attribute 'item'

Am I doing something wrong? I would appreciate if someone can give me a clue in order to solve this issue.

**Comment by rainLiuplus** [comment]
Hi @dhorka , please refer to [How to load the converted PyTorch model](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq). Thanks!

**Comment by dhorka** [comment]
Hi @rainLiuplus, thanks , this solved my issue! Sorry for have not read it before. I did not found this document :( I would like to ask another doubt. The idea of convert this model to pytorch is because I would like to retrain the model. Is there any issue or something that I need to take into account to re-train a model converted by mmdnn?

**Comment by rainLiuplus** [comment]
Hi @dhorka, the converted model file `.py ` only contains the definition of network architecture and the `.npy` file is the weights. So for re-training the model, in addition to loading the model, you also need to write some training codes to train the model. Thanks!

**Comment by xeroxM** [comment]
Hey @dhorka! I'm trying the exact same thing as you. Converting the places365 caffe pre-trained models to pytorch. In your post you state that, the conversion went without any problems. Sadly not for me, I'm running into some issue: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1521: ordinal not in range(128).

Maybe you had that issue before and solved it somehow?

Running this command:
mmconvert --srcFramework caffe --inputWeight vgg16_places365.caffemodel --inputNetwork deploy_vgg16_places365.prototxt --dstFramework pytorch -om vgg16places.pth

**Comment by sagarkalburgi** [comment]
Hi @dhorka,

how were you able to convert the caffemodel to torch model? I keep getting the following error:
```
(caffe) D:\dev\MasterThesis\DNN\Caffe2Pytorch>mmconvert --srcFramework caffe --inputWeight vgg16_hybrid1365.caffemodel --inputNetwork deploy_vgg16_hybrid1365.prototxt --dstFramework pytorch -om vgg16_hybrid1365.pth

------------------------------------------------------------
    WARNING: PyCaffe not found!
    Falling back to a pure protocol buffer implementation.
    * Conversions will be drastically slower.
    * This backend is UNTESTED!
------------------------------------------------------------

Type                 Name                                          Param               Output
----------------------------------------------------------------------------------------------
Data                 data                                             --    (10, 3, 224, 224)
Convolution          conv1_1                               (3, 3, 3, 64)   (10, 64, 224, 224)
ReLU                 relu1_1                                          --   (10, 64, 224, 224)
Convolution          conv1_2                              (3, 3, 64, 64)   (10, 64, 224, 224)
ReLU                 relu1_2                                          --   (10, 64, 224, 224)
Pooling              pool1                                            --   (10, 64, 112, 112)
Convolution          conv2_1                             (3, 3, 64, 128)  (10, 128, 112, 112)
ReLU                 relu2_1                                          --  (10, 128, 112, 112)
Convolution          conv2_2                            (3, 3, 128, 128)  (10, 128, 112, 112)
ReLU                 relu2_2                                          --  (10, 128, 112, 112)
Pooling              pool2                                            --    (10, 128, 56, 56)
Convolution          conv3_1                            (3, 3, 128, 256)    (10, 256, 56, 56)
ReLU                 relu3_1                                          --    (10, 256, 56, 56)
Convolution          conv3_2                            (3, 3, 256, 256)    (10, 256, 56, 56)
ReLU                 relu3_2                                          --    (10, 256, 56, 56)
Convolution          conv3_3                            (3, 3, 256, 256)    (10, 256, 56, 56)
ReLU                 relu3_3                                          --    (10, 256, 56, 56)
Pooling              pool3                                            --    (10, 256, 28, 28)
Convolution          conv4_1                            (3, 3, 256, 512)    (10, 512, 28, 28)
ReLU                 relu4_1                                          --    (10, 512, 28, 28)
Convolution          conv4_2                            (3, 3, 512, 512)    (10, 512, 28, 28)
ReLU                 relu4_2                                          --    (10, 512, 28, 28)
Convolution          conv4_3                            (3, 3, 512, 512)    (10, 512, 28, 28)
ReLU                 relu4_3                                          --    (10, 512, 28, 28)
Pooling              pool4                                            --    (10, 512, 14, 14)
Convolution          conv5_1                            (3, 3, 512, 512)    (10, 512, 14, 14)
ReLU                 relu5_1                                          --    (10, 512, 14, 14)
Convolution          conv5_2                            (3, 3, 512, 512)    (10, 512, 14, 14)
ReLU                 relu5_2                                          --    (10, 512, 14, 14)
Convolution          conv5_3                            (3, 3, 512, 512)    (10, 512, 14, 14)
ReLU                 relu5_3                                          --    (10, 512, 14, 14)
Pooling              pool5                                            --      (10, 512, 7, 7)
InnerProduct         fc6                                   (25088, 4096)     (10, 4096, 1, 1)
ReLU                 relu6                                            --     (10, 4096, 1, 1)
Dropout              drop6                                            --     (10, 4096, 1, 1)
InnerProduct         fc7                                    (4096, 4096)     (10, 4096, 1, 1)
ReLU                 relu7                                            --     (10, 4096, 1, 1)
Dropout              drop7                                            --     (10, 4096, 1, 1)
InnerProduct         fc8a                                   (4096, 1365)     (10, 1365, 1, 1)
Softmax              prob                                             --     (10, 1365, 1, 1)
IR network structure is saved as [647d2f5e4bfa4004b35a3d5c90892b63.json].
IR network structure is saved as [647d2f5e4bfa4004b35a3d5c90892b63.pb].
IR weights are saved as [647d2f5e4bfa4004b35a3d5c90892b63.npy].
Parse file [647d2f5e4bfa4004b35a3d5c90892b63.pb] with binary format successfully.
Target network code snippet is saved as [vgg16_hybrid1365.py].
Target weights are saved as [647d2f5e4bfa4004b35a3d5c90892b63.npy].
Traceback (most recent call last):
  File "D:\Users\KalburgS\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Users\KalburgS\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Users\KalburgS\Anaconda3\Scripts\mmconvert.exe\__main__.py", line 7, in <module>
  File "D:\Users\KalburgS\Anaconda3\lib\site-packages\mmdnn\conversion\_script\convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "D:\Users\KalburgS\Anaconda3\lib\site-packages\mmdnn\conversion\_script\dump_code.py", line 32, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath)
  File "D:\Users\KalburgS\Anaconda3\lib\site-packages\mmdnn\conversion\pytorch\saver.py", line 5, in save_model
    model = MainModel.KitModel(weight_filepath)
  File "vgg16_hybrid1365.py", line 28, in __init__
    self.conv1_1 = self.__conv(2, name='conv1_1', in_channels=3, out_channels=64, kernel_size=(3, 3), stride=(1, 1), groups=1, bias=True)
  File "vgg16_hybrid1365.py", line 118, in __conv
    layer.state_dict()['bias'].copy_(torch.from_numpy(_weights_dict[name]['bias']))
RuntimeError: output with shape [64] doesn't match the broadcast shape [1, 1, 1, 64]
```
I have tried it in windows 10 and VB. Any suggestions are highly appreciated.
