### ISSUE TITLE
Caffe to IR fails on TypeError

### ISSUE THREAD

**Issue by jsigee87** [Microsoft/MMdnn#421]
Platform (like ubuntu 16.04/win10):
Ubuntu 16.04

Python version:
3.5.2 inside virtual environment

Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe, not installed. Trying to convert pretrained Caffe model.

Destination framework with version (like CNTK 2.3 with GPU):
IR

Pre-trained model path (webpath or webdisk path):
https://gist.github.com/GilLevi/54aee1b8

The first model located under "Emotion Classification CNN- RGB".

Running scripts:
I attempted to run the intermediate command given in the Caffe Readme, with the ultimate goal of conversion to PyTorch.

Running the command:
`mmtoir -f caffe -n deploy.prototxt -w EmotiW_VGG_S.caffemodel -o model_ir`

fails with error:
```
Traceback (most recent call last):
  File "/home/johnsigmon/programming/ml-sandbox/.env/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
TypeError: 'NoneType' object is not subscriptable
```

I used `coremltools` to convert the caffe model to CoreML format to ensure there were no obvious issues with the way the model was saved. Any advice is appreciated!

**Comment by jsigee87** [comment]
Thanks! After providing an input shape, I get a failure due to Caffe not being installed (not configured correctly in my case). I didn't realize Caffe was a dependency, we can assume it works if I have Caffe installed and close this if you want. I wasted most of a day trying to correctly configure Caffe recently and have no interest in completing that installation. 

Just for an FYI, my error is now:
```
$ mmtoir -f caffe -n deploy.prototxt --inputShape 3,224,224 -w EmotiW_VGG_S.caffemodel -o model_ir
Traceback (most recent call last):
  File "/home/johnsigmon/programming/ml-sandbox/.env/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 16, in _convert
    transformer = CaffeTransformer(args.network, args.weights, "tensorflow", inputshape[0], phase = args.caffePhase)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/caffe/transformer.py", line 309, in __init__
    model = get_caffe_resolver().NetParameter()
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/caffe/resolver.py", line 32, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/caffe/resolver.py", line 8, in __init__
    self.import_caffe()
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/mmdnn/conversion/caffe/resolver.py", line 22, in import_caffe
    self.caffepb = self.caffe.proto.caffe_pb2
AttributeError: module 'caffe' has no attribute 'proto'
```

**Comment by namizzz** [comment]
> Source framework with version (like Tensorflow 1.4.1 with GPU):
> Caffe, not installed. Trying to convert pretrained Caffe model.

You need to install Caffe first. Thanks!
