### ISSUE TITLE
Error converting keras model to pytorch

### ISSUE THREAD

**Issue by nischa564** [microsoft/MMdnn#915]
Platform (like ubuntu 16.04/win10): win10

Python version: 3.8.5

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 2.3.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU): Pytorch 1.7.1

Pre-trained model path (webpath or webdisk path): https://keras.io/examples/vision/mnist_convnet/

Running scripts: mmconvert -sf keras -my_h5_model.h5 -df pytorch -om test_m.pth

Hello, I try to convert a keras model to a pytorch model. The error I get is:

Traceback (most recent call last):
  File "c:\users\nisch\anaconda3\envs\jntorchenv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\nisch\anaconda3\envs\jntorchenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nisch\anaconda3\envs\jntorchenv\Scripts\mmconvert.exe\__main__.py", line 7, in <module>
  File "c:\users\nisch\anaconda3\envs\jntorchenv\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\users\nisch\anaconda3\envs\jntorchenv\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "c:\users\nisch\anaconda3\envs\jntorchenv\lib\site-packages\mmdnn\conversion\keras\keras2_parser.py", line 129, in __init__
    assert False
AssertionError

**Comment by nischa564** [comment]
Hello, I solved this problem by using different versions:

Python version: 3.6.12

Source framework with version (like Tensorflow 1.4.1 with GPU): Tensorflow 1.15.2

Destination framework with version (like CNTK 2.3 with GPU): Pytorch 0.4.0

But now I am getting this error:
Traceback (most recent call last):
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\mmdnn\conversion\keras\keras2_parser.py", line 104, in __init__
    from keras.applications.mobilenet import relu6
ImportError: cannot import name 'relu6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nisch\anaconda3\envs\mmdnne\Scripts\mmconvert.exe\__main__.py", line 7, in <module>
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\mmdnn\conversion\keras\keras2_parser.py", line 120, in __init__
    'DepthwiseConv2D': layers.DepthwiseConv2D
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\engine\sequential.py", line 300, in from_config
    custom_objects=custom_objects)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\engine\base_layer.py", line 1109, in from_config
    return cls(**config)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\layers\convolutional.py", line 490, in __init__
    **kwargs)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\layers\convolutional.py", line 117, in __init__
    self.kernel_initializer = initializers.get(kernel_initializer)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\initializers.py", line 508, in get
    return deserialize(identifier)
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\initializers.py", line 503, in deserialize
    printable_module_name='initializer')
  File "c:\users\nisch\anaconda3\envs\mmdnne\lib\site-packages\keras\utils\generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: GlorotUniform
