### ISSUE TITLE
mmconvert from pytorch to tensorflow:  'dict' object has no attribute 'state_dict'`

### ISSUE THREAD

**Issue by amaanda** [Microsoft/MMdnn#642]
Platform (like ubuntu 16.04/win10): win10

Python version: 3.6.8

Source framework with version (like Tensorflow 1.4.1 with GPU): pytorch 1.0

Destination framework with version (like CNTK 2.3 with GPU): tensorflow

Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1SJJx5-LFG3J3M99TrPMU-z6ZmgWynxo-/view

Running scripts:
`mmconvert -sf pytorch -iw "C:\Users\olhod\OneDrive\Documentos\models\resnet50.pth.tar" -df tensorflow -om .\resnet50_pth_to_tf.pb`

I am trying to convert the pre-trained Inplace_ABN model
I keep getting the following error:

`Traceback (most recent call last):
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\olhod\AppData\Local\Programs\Python\Python36\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\pytorch\pytorch_parser.py", line 83, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\pytorch\pytorch_graph.py", line 59, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "c:\users\olhod\appdata\local\programs\python\python36\lib\site-packages\torch\jit\__init__.py", line 200, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'dict' object has no attribute 'state_dict'`

Any help would be appreciated. Thanks!

**Comment by JiahaoYao** [comment]
Hi @amaanda, seems to have something to do with this issue: https://github.com/Microsoft/MMdnn/issues/527.

But for me, I got the issue:
```
Traceback (most recent call last):
  File "/anaconda3/envs/mmdnn/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/anaconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/anaconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/anaconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 86, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "/anaconda3/envs/mmdnn/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 59, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "/anaconda3/envs/mmdnn/lib/python3.5/site-packages/torch/jit/__init__.py", line 259, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'str' object has no attribute 'state_dict'
```

**Comment by amaanda** [comment]
@JiahaoYao with the same command?

**Comment by amaanda** [comment]
Apparently MMdnn [does not support pytorch 1.0.0 ](https://github.com/Microsoft/MMdnn/issues/608#issuecomment-471899162).

**Comment by linmajia** [comment]
@amaanda, thank you very much for the feedback. We only support PyTorch 0.4.0 right now, and will support 1.0.x in near future.

Thanks.

**Comment by JiahaoYao** [comment]
Hi @amaanda, I looked into your model. I found your model only contained the weight, i.e. `state_dict`. In this way, the `pth` only has the weight and the model info (how the model is connected). You need to save the whole model instead of the state_dict. You can also refer to https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq.

**Comment by amaanda** [comment]
@JiahaoYao I see. I'm sorry, I'm only beginning to work with Pytorch so I'm still a bit lost. Thanks a lot!

**Comment by allendred** [comment]
I meet the same error，pth url=“https://download.pytorch.org/models/resnet101-5d3b4d8f.pth”，pytorch==0.4.0

**Comment by EricKani** [comment]
Hi @amaanda ,

I am sorry to bother you... In the contrary, I am a new man in tensorflow. I have some questions bothering me. Hope you can help me:

1 Is there some difference between "pb" and "ckpt"? 
2 Can we fine-tuning a tensorflow model begin with a "pb" format model?
3 Is "ckpt" a strict format in tensorflow? 
For example, "pth" is just a casual name in pytorch. We also can use "pt", "pa", "pv", etc as our saved pytorch model's name. 
In tensorflow, can we save tensorflow model in another name?  Like "model.pth.meta/index/data" instead of "model.ckpt.meta/index/data"?

Thank you very much!

Best,

pengbol

**Comment by EricKani** [comment]
Hi @linmajia ,

Have we supported pytorch 1.0 or higher version now? 

Thank you~

Best,

pengbol

**Comment by rainLiuplus** [comment]
Hi @EricKani, I am sorry that we only support pytorch 0.4.0 now, since different versions of pytorch vary greatly.

**Comment by EricKani** [comment]
Hi @rainLiuplus ,

Thanks for your reply. I understand what you mean. 

By the way, do you know is there a way to transfer pytorch model to ".ckpt" format tensorflow model? I have not found it by now... ONNX method can only transfer pytorch model to ".pb" format tf model...

Thank you,

Best,

pengbol
