### ISSUE TITLE
relu6 when convert tensorflow to caffe

### ISSUE THREAD

**Issue by hnuhchen** [microsoft/MMdnn#798]
Platform (like ubuntu 16.04/win10):
ubuntu1604
Python version:
3.5.2
Source framework with version (like Tensorflow 1.4.1 with GPU):
tensorflow
Destination framework with version (like CNTK 2.3 with GPU):
caffe
Pre-trained model path (webpath or webdisk path):

Running scripts:

Hello, everyone.
I have a question about relu6 of tensorflow. 
The code is here.
```
def emit_Relu6(self, IR_node):
    self.emit_Relu(IR_node)
```
So, is relu6 the same as relu?

**Comment by linmajia** [comment]
@hnuhchen , thank you very much for the feedback. Which version of MMdnn are you using? The emit_Relu6() in the latest 0.2.5 release is as follows:

```Python
# mmdnn/conversion/tensorflow/tensorflow_emitter.py, line 443
def emit_Relu6(self, IR_node):
        return self._emit_unary_operation(IR_node, 'nn.relu6')
```

**Comment by linmajia** [comment]
It seems that we could use the Clip layer to simulate ReLu6. Strangely, such layer is not listed in the documentation of [Caffe layers](http://caffe.berkeleyvision.org/tutorial/layers.html).

**Comment by hnuhchen** [comment]
> @hnuhchen , thank you very much for the feedback. [ReLu6](https://www.tensorflow.org/api_docs/python/tf/nn/relu6) computes rectified linear 6: min(max(features, 0), 6), which is not the same as [ReLu](https://www.tensorflow.org/api_docs/python/tf/nn/relu). However, Caffe does not implement ReLu6 yet, so we use ReLu instead.

Thank you for your answer. 
The output of relu is not the same as the output of relu6, so the modification may cause problems of consistence

**Comment by hnuhchen** [comment]
> @hnuhchen, it seems that we could use the Clip layer to simulate ReLu6. Please help test the [pull request](https://github.com/microsoft/MMdnn/pull/803/files). Strangely, the Clip layer is not listed in the documentation of [Caffe layers](http://caffe.berkeleyvision.org/tutorial/layers.html).
Thank you.
Unfortunately, my plateform does not support clip layer now, i cannot test your pull request.
