### ISSUE TITLE
emit_RNNs function doesnt exist

### ISSUE THREAD

**Issue by yunti123** [Microsoft/MMdnn#497]
Platform (like ubuntu 16.04/win10): linux mint(ubuntu 16.04)

Python version: 3.5.2

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.9.0
Running scripts:

AttributeError: 'TensorflowEmitter' object has no attribute 'emit_RNNs'

In  MMdnn/mmdnn/conversion/tensorflow/tensorflow_emitter.py and 
in 451.line and 455.line return self.emit_RNNs(IR_node, "LSTM")
but this line give error "AttributeError: 'TensorflowEmitter' object has no attribute 'emit_RNNs'
"  and in tensorflow_emitter.py there is no function named emit.RNNs()

**Comment by rainLiuplus** [comment]
Hi @yunti123 , currently MMdnn  does not support RNN related operators. We are going to develop them. Thanks!

**Comment by yunti123** [comment]
Thank you for your reply
