### ISSUE TITLE
Pytorch to IR AttributeError: 'OrderedDict' object has no attribute 'state_dict'

### ISSUE THREAD

**Issue by muzi-8** [Microsoft/MMdnn#413]
Platform (like ubuntu 16.04):

Python version:

Source framework with version (like pytorch0.40 with CPU):

Destination framework with version (like tensorflow1.8.0 with CPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
mmtoir -f pytorch -d inception_v3 --inputShape 3,299,299 -n /**/.torch/models/inception_v3_google-1a9a5a14.pth

show Error Information below:

Traceback (most recent call last):
  File "/usr/local/bin/mmtoir", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmtoir')()
  File "/**/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/**/.local/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(args.network, inputshape[0])
  File "/**/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 81, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "/**/.local/lib/python2.7/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 59, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "/**/.local/lib/python2.7/site-packages/torch/jit/__init__.py", line 81, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'OrderedDict' object has no attribute 'state_dict'
Thanks!

**Comment by namizzz** [comment]
Hi @muzi-8 , please refer to [this](https://github.com/pytorch/pytorch/issues/2767). Thanks!

**Comment by muzi-8** [comment]
@namizzz Thanks for your reply! However, I could't solve it by myself, so can you say it more detailed? I mainly refer to the document [PyTorch README](https://github.com/Microsoft/MMdnn/tree/master/mmdnn/conversion/pytorch)

**Comment by HongChow** [comment]
@muzi-8 I've met the very problem you presented in the OP. File "/usr/local/lib/python3.5/dist-packages/torch/jit/__init__.py", line 259, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

How did you solve the problem??

**Comment by serser** [comment]
same here with py3.6.4, torch1.1.0, mmdnn 0.2.5.

**Comment by NguyenDangBinh** [comment]
dear,
Did you solve AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict' ?

**Comment by vizakshat** [comment]
Has anyone solved it?
