### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'type'

### ISSUE THREAD

**Issue by Zhang-Jack** [microsoft/MMdnn#652]
Platform: Ubuntu 18.04

Python version: 3.7.3

Source framework with version : Tensorflow 1.13.1 with GPU

Destination framework with version: Caffe 1.0 with GPU

Pre-trained model path :
you can get them through the commands below:
git clone https://github.com/cchen156/Learning-to-See-in-the-Dark.git
python download_models.py

Running scripts:
cd checkpoint/Sony
mmconvert -sf tensorflow -in model.ckpt.meta -iw model.ckpt --dstNode Mean -df caffe -om Sony.caffemodel

Warning: Graph Construct a self-loop node g_conv4_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv4_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv4_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv5_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv5_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv4_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv6_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv6_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv3_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv7_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv7_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv2_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv8_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv8_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv1_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv9_1/Maximum. Ignored.
Warning: Graph Construct a self-loop node g_conv9_2/Maximum. Ignored.
Warning: Graph Construct a self-loop node DepthToSpace. Ignored.
Traceback (most recent call last):
  File "/home/ljack6996/anaconda3/bin/mmconvert", line 10, in <module>
    sys.exit(_main())
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 144, in run
    super(CaffeEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 22, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 59, in save_code
    code = self.gen_code(phase)
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 132, in gen_code
    func(current_node)   
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 197, in emit_Conv
    pad_h, pad_w = self._get_symmetric_padding(IR_node)   
  File "/home/ljack6996/anaconda3/lib/python3.7/site-packages/mmdnn/conversion/caffe/caffe_emitter.py", line 160, in _get_symmetric_padding   
    if IR_parent_node.type == 'Pad':   
AttributeError: 'NoneType' object has no attribute 'type'   

Would you please help me to figure out how to fix it? Thank you in advance!

**Comment by JiahaoYao** [comment]
Hi @Zhang-Jack, is the architecture [https://github.com/cchen156/Learning-to-See-in-the-Dark/blob/master/train_Sony.py#L44-L82](https://github.com/cchen156/Learning-to-See-in-the-Dark/blob/master/train_Sony.py#L44-L82)? It seems to fail at the max pooling. That is weird. Besides, I think for now, `tf.depth_to_space` and `tf.space_to_depth` are not supported.

**Comment by Zhang-Jack** [comment]
@JiahaoYao Thank you for your reply! 
And yes, the link you mentioned is exactly project that I am trying to convert. And I am wondering wether it is some error about placeholder of [None, None, None, 4] of input, which cause the padding of IR node gets the NoneType. 
And if tf.depth_tospace and tf.space_to_depth are not supported for now, do you mean that I need to re-write the caffe codes and re-train the model instead of using this pre-trained model? What's your suggestion? 
Thank you again for your help!

**Comment by JiahaoYao** [comment]
Hi @Zhang-Jack, in my opinion, if you can convert the network part until https://github.com/cchen156/Learning-to-See-in-the-Dark/blob/master/train_Sony.py#L45-L80. (Just all the part before `tf.space_to_depth`.), then what you only need is just to implement `tf.space_to_depth` in caffe. I mean `tf.space_to_depth` is just transformation of your tensor, and does not contain the parameters. That is my suggestion, and hope that works for you.

**Comment by Zhang-Jack** [comment]
@JiahaoYao , thank you for your advice!
Sorry but I am just a newbie in this feild, and I don't know how to convert the network part by part. Would you please show me how to do that or just provide an instruction document? 
For now, I can get that whole network converted to the IR file format.
