### ISSUE TITLE
Convert Keras to onnx

### ISSUE THREAD

**Issue by SherlockBlaze** [Microsoft/MMdnn#358]
Platform: Mac High Sierra

Python version: 3.6

Source framework with version (like Tensorflow 1.4.1 with GPU): 1.10.0

Destination framework with version (like CNTK 2.3 with GPU): onnx

Running scripts:  mmconvert -sf keras -iw densenet121.keras -df onnx -om densenet121.onnx

Hi, here is a question.
I tried the example describe in onnx's Readme. When I finished the first step and tried to convert the keras model to a onnx model, something was wrong. Here's the complete info:

Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/sherlockblaze/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 105, in __init__
    'relu6': _keras.applications.mobilenet.relu6,
AttributeError: module 'keras.applications.mobilenet' has no attribute 'relu6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sherlockblaze/anaconda3/envs/python3.6/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/Users/sherlockblaze/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/Users/sherlockblaze/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/Users/sherlockblaze/anaconda3/envs/python3.6/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 115, in __init__
    'relu6': mobilenet.relu6,

**Comment by YusukeO** [comment]
In my case, updating mmdnn to latest version (0.2.3) solved the same problem.

**Comment by SherlockBlaze** [comment]
@YusukeO That's weird. In my case, the version has already be the 0.2.3

**Comment by SherlockBlaze** [comment]
@YusukeO I reinstalled it and solved the problem. Thanks a lot.
