### ISSUE TITLE
Convert tensorflow ckpt to onnx failed

### ISSUE THREAD

**Issue by peteryang1** [Microsoft/MMdnn#445]
Platform (like ubuntu 16.04/win10):win10

Python version:3.6.6

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow1.8 with cpu

Destination framework with version (like CNTK 2.3 with GPU):onnx

Pre-trained model path (webpath or webdisk path):ordinary mnist ckpt

Running scripts:
==
`mmconvert.exe -sf tensorflow -in D:\code\tensorflow\ckpt\model.ckpt.meta -iw D:\code\tensorflow\ckpt\model.ckpt -df onnx -om .\result.onnx --dstNodeName add_3 --inNodeName input_holder --inputShape 1,784`

Error:
===
Traceback (most recent call last):
  File "D:\software\python3.6\Scripts\mmconvert-script.py", line 11, in <module>
    load_entry_point('mmdnn==0.2.3', 'console_scripts', 'mmconvert')()
  File "D:\software\python3.6\lib\site-packages\mmdnn-0.2.3-py3.6.egg\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "D:\software\python3.6\lib\site-packages\mmdnn-0.2.3-py3.6.egg\mmdnn\conversion\_script\convertToIR.py", line 64, in _convert
    parser = TensorflowParser(args.network, args.weights, args.dstNodeName, inputshape[0], args.inNodeName)
  File "D:\software\python3.6\lib\site-packages\mmdnn-0.2.3-py3.6.egg\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 246, in __init__
    transformed_graph_def = TransformGraph(model, in_nodes.keys(),
AttributeError: 'list' object has no attribute 'keys'

**Comment by peteryang1** [comment]
the input should be 4 dimensions.........

**Comment by ArtyZe** [comment]
@peteryang1 hello, have you done convert tf model to onnx successfully? I met some problems same with you. Help :(
