### ISSUE TITLE
Caffe to tensorflow fails with module 'tensorflow._api.v2.saved_model' has no attribute 'tag_constants'

### ISSUE THREAD

**Issue by Xodarap** [microsoft/MMdnn#853]
Platform (like ubuntu 16.04/win10):
Google colab

Python version:
Python 3.6.9

Source framework with version (like Tensorflow 1.4.1 with GPU):
Caffe 

Destination framework with version (like CNTK 2.3 with GPU):
Tensorflow 2.2.0

Pre-trained model path (webpath or webdisk path):
https://drive.google.com/file/d/1un5CjTz_49Lg6MTNQn99WD7FjFqEJGoY/view

Running scripts:
mmconvert --srcFramework caffe --inputWeight /tmp/nst/resnext50.caffemodel --inputNetwork /tmp/nst/resnext50_deploy.prototxt --dstFramework tensorflow --outputModel /tmp/nst/out

```
IR network structure is saved as [0c9f695fe76e4f5995839cd0e5264998.json].
IR network structure is saved as [0c9f695fe76e4f5995839cd0e5264998.pb].
IR weights are saved as [0c9f695fe76e4f5995839cd0e5264998.npy].
Parse file [0c9f695fe76e4f5995839cd0e5264998.pb] with binary format successfully.
Target network code snippet is saved as [0c9f695fe76e4f5995839cd0e5264998.py].
2020-06-15 17:56:54.639063: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/convert.py", line 112, in _main
    dump_code(args.dstFramework, network_filename + '.py', temp_filename + '.npy', args.outputModel, args.dump_tag)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/_script/dump_code.py", line 25, in dump_code
    save_model(MainModel, network_filepath, weight_filepath, dump_filepath, dump_tag)
  File "/usr/local/lib/python3.6/dist-packages/mmdnn/conversion/tensorflow/saver.py", line 8, in save_model
    tag_list = [tf.saved_model.tag_constants.TRAINING]
AttributeError: module 'tensorflow._api.v2.saved_model' has no attribute 'tag_constants'

**Comment by Xodarap** [comment]
This was fixed by switching to tensorflow 1.14. Did I miss somewhere that tensorflow 2 is not supported?

**Comment by linmajia** [comment]
@Xodarap , thank you very much for the feedback. Currently, we only support TensorFlow till 1.15.2 . We are working to support TensorFlow 2.x in the future.
