### ISSUE TITLE
pytorch2IR erro

### ISSUE THREAD

**Issue by allendred** [microsoft/MMdnn#688]
Platform (like ubuntu 16.04/win10):

Python version:3.5

Source framework with version (like Tensorflow 1.4.1 with GPU):pytorch0.4

Destination framework with version (like CNTK 2.3 with GPU):caffe

Pre-trained model path (webpath or webdisk path):resnet101  or xception

Running scripts:
Traceback (most recent call last):
  File "/home/anaconda3/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/anaconda3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/anaconda3/lib/python3.5/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/homeanaconda3/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 83, in __init__
    self.pytorch_graph = PytorchGraph(model)
  File "/home/anaconda3/lib/python3.5/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 59, in __init__
    self.state_dict = _unique_state_dict(self.model)
  File "/homeanaconda3/lib/python3.5/site-packages/torch/jit/__init__.py", line 200, in _unique_state_dict
    state_dict = module.state_dict(keep_vars=keep_vars)
AttributeError: 'collections.OrderedDict' object has no attribute 'state_dict'

**Comment by rainLiuplus** [comment]
Hi @allendred, please refer to [this](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/pytorch/README.md#faq).

**Comment by NguyenDangBinh** [comment]
hi @allendred , did you solve it?
