### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by jackchinor** [Microsoft/MMdnn#269]
Platform (like ubuntu 16.04/win10):
ubuntu 14.04

Python version:2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):

Destination framework with version (like CNTK 2.3 with GPU):

Pre-trained model path (webpath or webdisk path):

Running scripts:
 File "/home/shyf/anaconda2/envs/tensorflow/bin/mmtoir", line 11, in <module>
    sys.exit(_main())
  File "/home/shyf/anaconda2/envs/tensorflow/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 184, in _main
    ret = _convert(args)
  File "/home/shyf/anaconda2/envs/tensorflow/lib/python2.7/site-packages/mmdnn/conversion/_script/convertToIR.py", line 102, in _convert
    parser.run(args.dstPath)
  File "/home/shyf/anaconda2/envs/tensorflow/lib/python2.7/site-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/home/shyf/anaconda2/envs/tensorflow/lib/python2.7/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 311, in gen_IR
    func(current_node)
  File "/home/shyf/anaconda2/envs/tensorflow/lib/python2.7/site-packages/mmdnn/conversion/tensorflow/tensorflow_parser.py", line 646, in rename_FusedBatchNorm
    self.set_weight(source_node.name, 'scale', self.ckpt_data[scale.name])
AttributeError: 'NoneType' object has no attribute 'name'
(tensorflow) shyf@SHYFSer:~/work/goodix_qxg/tf2/checkpoint_autoenc_0531_SSIMAdam$ 

when I convert my own tensorflow model to IR file, there is a  problem happens , Can anyone help me figure it out?
Thanks!

**Comment by JiahaoYao** [comment]
Hi @jackchinor , 
If you follow the [Meta File Graph Visualization](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#meta-file-graph-visualization) here, you can probably visualize your graph. 

If the `batchnorm`  layer is like this, then it can be easily converted.
![image](https://user-images.githubusercontent.com/20907377/41885148-3bdc8f4e-7929-11e8-9e2f-425ec70b9022.png)

However, if the `batchnorm` layer is like this, it needs more steps.

![image](https://user-images.githubusercontent.com/20907377/41885213-801ced0c-7929-11e8-8083-1f63fa619b03.png)

That is because the `mmdnn` uses the input information to build the graph. 

For the first type, its input is like this:
![image](https://user-images.githubusercontent.com/20907377/41885249-b0f31816-7929-11e8-9f72-903ce2344bff.png)

In contrast, for the second type, its input is like this
![image](https://user-images.githubusercontent.com/20907377/41885269-cd85e3fa-7929-11e8-9d9c-f2e2da58ca23.png)

I think that is why `AttributeError: 'NoneType' object has no attribute 'name'` .

**Comment by JiahaoYao** [comment]
In this situation, if there is a `is_training` parameter and set it to `False` and then reload and dump the model, this might reduce the second type to the first type of `batchnorm`.

**Comment by criminalking** [comment]
Hi @JiahaoYao ,
I also encountered the same problem. Could you please share some sample codes of the solution you mentioned above? I'm a newbie in tensorflow. Really appreciate your help!

**Comment by asa008** [comment]
Hi, @JiahaoYao , @jackchinor , @criminalking 
I have met almost the same problem, could you tell me how to solve it?
```
  File "c:\users\qjhs\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 420, in gen_IR
    func(current_node)
  File "c:\users\qjhs\appdata\local\programs\python\python36\lib\site-packages\mmdnn\conversion\tensorflow\tensorflow_parser.py", line 810, in rename_FusedBatchNorm
    self.set_weight(source_node.name, 'mean', self.ckpt_data[mean.name])
AttributeError: 'NoneType' object has no attribute 'name'
```
Thank you

**Comment by machanic** [comment]
@asa008 Do you solve this problem? I encounter the same issue!

**Comment by machanic** [comment]
I posted an issue here: https://github.com/microsoft/MMdnn/issues/925
