### ISSUE TITLE
TypeError: forward() missing 8 required positional arguments while converting pytorch to IR

### ISSUE THREAD

**Issue by tomshalini** [microsoft/MMdnn#794]
I am trying to convert pre-trained stereo rcnn pytorch model to IR. This model is taking left and right view images. I dont understand how to give input shape for multiple inputs. Code can be find at below link. Also, pretrained model link is mentioned below. 

Github link for Stereo Rcnn: https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN

Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1MlNXZbAX-JmR4ENeMETM28h_dGQkgUb6/view

Error: 
Traceback (most recent call last):
  File "/home/anaconda3/envs/env_stereo/bin/mmtoir", line 8, in <module>
    sys.exit(_main())
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 92, in _convert
    parser = PytorchParser(model, inputshape[0])
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_parser.py", line 86, in __init__
    self.pytorch_graph.build(self.input_shape)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_graph.py", line 122, in build
    trace, output = torch.jit.get_trace_graph(self.model, (dummy_input, ))
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/jit/__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/jit/__init__.py", line 251, in forward
    out = self.inner(*trace_inputs)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 487, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in _slow_forward
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 8 required positional arguments: 'im_right_data', 'im_info', 'gt_boxes_left', 'gt_boxes_right', 'gt_boxes_merge', 'gt_dim_orien', 'gt_kpts', and 'num_boxes'

Platform (like ubuntu 16.04/win10): ubuntu18.04

Python version: Python 3.6.9

Source framework with version (like Tensorflow 1.4.1 with GPU): Pytorch 1.0.0

Destination framework with version (like CNTK 2.3 with GPU): Tensorflow any

Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1MlNXZbAX-JmR4ENeMETM28h_dGQkgUb6/view

Running scripts:
mmtoir -f pytorch -d stereo_rcnn --inputShape 3,600,600 -n /home/Models/Stereo-RCNN-1.0/models_stereo/stereo_rcnn_testing_1_6477.pth

Can anyone help me to resolve this error?

**Comment by linmajia** [comment]
@tomshalini , thank you very much for the feedback. It maybe caused by the unsupported PyTorch version. Currently, we only support PyTorch 0.4.0.

**Comment by tomshalini** [comment]
How to convert a model from pytorch to tensorflow if model has multiple inputs? Please advice on this.

**Comment by JiahaoYao** [comment]
Currently, the platform has not supported multiple inputs yet. And the error might be also caused by the bounding box region proposal because of the following error -- `TypeError: forward() missing 8 required positional arguments: 'im_right_data', 'im_info', 'gt_boxes_left', 'gt_boxes_right', 'gt_boxes_merge', 'gt_dim_orien', 'gt_kpts', and 'num_boxes'`. This might be too flexible to convert from pytorch to tensorflow.
