### ISSUE TITLE
ERROR when converting tensorflow to pytorch model [AttributeError: 'NoneType' object has no attribute 'real_variable_name']

### ISSUE THREAD

**Issue by joaoantoniocn** [Microsoft/MMdnn#500]
Platform (like ubuntu 16.04/win10): ubuntu 18.04.1 LTS

Python version:  python 3.6.5

Source framework with version (like Tensorflow 1.4.1 with GPU): tensorflow 1.8.0

Destination framework with version (like CNTK 2.3 with GPU): pytorch

Pre-trained model path (webpath or webdisk path): https://drive.google.com/file/d/1nBmggq4uixcI2AtucGu5nsa28dJRwkIz/view

Running scripts: mmconvert -sf tensorflow -in faceres_ms/graph.meta -iw faceres_ms/ckpt-320000 --dstNode outputs -df pytorch -om pytorch-model.pth

----------------------------
 Hi guys, 

when I'm trying to convert tensorflow to pytorch I'm getting this error:

AttributeError: 'NoneType' object has no attribute 'real_variable_name'

I have notticed that the script can generate the .json, .npy, and .pb files alright, but when it tries to get these files to convert to .pth file it outpust the error.

**Comment by joaoantoniocn** [comment]
Traceback (most recent call last):
  File "/home/joao/projetos/DocFace-master/venv/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 108, in _main
    ret = IRToCode._convert(code_args)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/_script/IRToCode.py", line 61, in _convert
    emitter.run(args.dstModelPath, args.dstWeightPath, args.phase)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 44, in run
    super(PytorchEmitter, self).run(dstNetworkPath, dstWeightPath, phase)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 21, in run
    self.save_code(dstNetworkPath, phase)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/common/DataStructure/emitter.py", line 53, in save_code
    code = self.gen_code(phase)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 95, in gen_code
    line = func(current_node)
  File "/home/joao/projetos/DocFace-master/venv/lib/python3.6/site-packages/mmdnn/conversion/pytorch/pytorch_emitter.py", line 331, in emit_Relu
    self.IR_graph.get_parent(IR_node.name, [0]).real_variable_name))
AttributeError: 'NoneType' object has no attribute 'real_variable_name'

**Comment by suikammd** [comment]
Hey, do you solve this problem?

**Comment by joaoantoniocn** [comment]
Not yet
