### ISSUE TITLE
RELU Error on transferring Keras weight to pytorch

### ISSUE THREAD

**Issue by junikkoma** [Microsoft/MMdnn#920]
Platform (like ubuntu 16.04/win10): Ubuntu 18.04, using docker image provided

Python version: 3.6.9

Source framework with version (like Tensorflow 1.4.1 with GPU): Keras 2.1.6 / 2.2.2, tensorflow 2.2.0

Destination framework with version (like CNTK 2.3 with GPU): pytorch 1.8.1

Pre-trained model path (webpath or webdisk path): custom weights

Running scripts: $ mmconvert -sf keras -df pytorch -om trial.pth -iw my_custom_weights.h5

On running script above under Keras 2.2.2 enviornment, i got following errrors:
```
Traceback (most recent call last):
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 104, in __init__
    from keras.applications.mobilenet import relu6
ImportError: cannot import name 'relu6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junikkoma/.local/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 120, in __init__
    'DepthwiseConv2D': layers.DepthwiseConv2D
  File "/home/junikkoma/.local/lib/python3.6/site-packages/keras/engine/saving.py", line 258, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.
```

on inspecting first error on keras2_parser.py", line 104, I noticed downgrading Keras version to 2.1.6 might help.
on my second trial(with same script) under keras 2.1.6 enviornment, i got following errors
```
Traceback (most recent call last):
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 110, in __init__
    'DepthwiseConv2D': _keras.applications.mobilenet.DepthwiseConv2D
  File "/home/junikkoma/.local/lib/python3.6/site-packages/keras/models.py", line 268, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/junikkoma/.local/bin/mmconvert", line 8, in <module>
    sys.exit(_main())
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/home/junikkoma/.local/lib/python3.6/site-packages/mmdnn/conversion/keras/keras2_parser.py", line 119, in __init__
    'relu6': layers.ReLU(6, name='relu6'),
AttributeError: module 'keras.layers' has no attribute 'ReLU'
```

Sine similar errors with ReLU and Conv2D, I was wondering if there would be some solution

**Comment by tsly123** [comment]
Hi,

Have you solve this problem? I met this same problem and did exactly what you did.
I tried with many tensorflow and keras version. Still same error
