### ISSUE TITLE
Module 'keras.applications.mobilenet' has no attribute 'relu6'

### ISSUE THREAD

**Issue by michhar** [Microsoft/MMdnn#344]
Platform (like ubuntu 16.04/win10):  win10

Python version:  3.6.6

Source framework with version (like Tensorflow 1.4.1 with GPU):  Keras 2.2.2, Tensorflow 1.9.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU):  PyTorch 0.4.1 with GPU

Pre-trained model path (webpath or webdisk path):  https://drive.google.com/open?id=15brUl4NgXHUnkjMoriE0AOlTdaigvqHb (a Tiny YOLOv3 architecture trained two-class object detection model)

Running scripts: TBD (or WIP)

Command and error:

```
(py36_aml) C:\Users\michhar.REDMOND\Documents\bin\github\keras-yolo3\logs\002>mmconvert -sf keras -iw ep510-loss18.510-val_loss16.429.h5 -df pytorch -om ep510-loss18.510-val_loss16.429_pytorch.model
Using TensorFlow backend.
Traceback (most recent call last):
  File "c:\anaconda3\envs\py36_aml\lib\site-packages\mmdnn\conversion\keras\keras2_parser.py", line 105, in __init__
    'relu6': _keras.applications.mobilenet.relu6,
AttributeError: module 'keras.applications.mobilenet' has no attribute 'relu6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\envs\py36_aml\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py36_aml\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py36_aml\Scripts\mmconvert.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\py36_aml\lib\site-packages\mmdnn\conversion\_script\convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "c:\anaconda3\envs\py36_aml\lib\site-packages\mmdnn\conversion\_script\convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "c:\anaconda3\envs\py36_aml\lib\site-packages\mmdnn\conversion\keras\keras2_parser.py", line 115, in __init__
    'relu6': mobilenet.relu6,
AttributeError: module 'keras_applications.mobilenet' has no attribute 'relu6'
```

* Love this project and any recommendations (looks like a recent [code update](https://github.com/Microsoft/MMdnn/commit/6b85d4567125676aa38e04e41b508d7cc15f57f1) may be fixing this)
* Perhaps it's something really simple (I'm new to this code).  Just let me know what I can try.  
* The model is a tiny YOLOv3 keras model and I wish to port to a PyTorch model - is this supported or will be?

Thanks!

**Comment by namizzz** [comment]
Hi @michhar , there is no **keras_applications.mobilenet.relu6** in keras 2.2.2. We have fixed the problem in [PR](https://github.com/Microsoft/MMdnn/commit/6b85d4567125676aa38e04e41b508d7cc15f57f1#diff-4a0cfa0dc00993d2eddc37d1e4dff875). You can try the newest code! 

And it seems that there is a custom objects 'yolo_head' in your model , you need to edit the code in **load_model** part to fix it.

**Comment by haohuiDL** [comment]
> Hi @michhar , there is no **keras_applications.mobilenet.relu6** in keras 2.2.2. We have fixed the problem in [PR](https://github.com/Microsoft/MMdnn/commit/6b85d4567125676aa38e04e41b508d7cc15f57f1#diff-4a0cfa0dc00993d2eddc37d1e4dff875). You can try the newest code!
> 
> And it seems that there is a custom object 'yolo_head' in your model , you need to edit the code in **load_model** part to fix it.

Hi @namizzz I have the same problem in ubuntu16.04 with python 2.7,  I have reinstalled or upgrade mmdnn, still not help.
**keras: 2.2.2**
**mmdnn: 0.2.3**
Error Information:
```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/bin/mmconvert", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convert.py", line 102, in _main
    ret = convertToIR._convert(ir_args)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 46, in _convert
    parser = Keras2Parser(model)
  File "/usr/local/lib/python2.7/dist-packages/mmdnn/conversion/keras/keras2_parser.py", line 115, in __init__
    'relu6': mobilenet.relu6,
AttributeError: 'module' object has no attribute 'relu6'
```
