### ISSUE TITLE
MXNet -> Tensorflow: Cannot use converted tensorflow .pb file (Error parsing message)

### ISSUE THREAD

**Issue by WIll-Xu35** [Microsoft/MMdnn#587]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version: Python 3.5.2

Source framework with version (like Tensorflow 1.4.1 with GPU): mxnet 1.3.0 with GPU

Destination framework with version (like CNTK 2.3 with GPU): tensorflow 1.8 with GPU

Pre-trained model path (webpath or webdisk path): https://drive.google.com/open?id=1p5akk8_ur36xJlXIKPju1qzm6VzkdNas

Running scripts:
mmconvert -sf mxnet -in model-symbol.json -iw model-0000.params --inputShape 3,112,112 --dstNodeName fc1 -df tensorflow -om ./test

Hi, my problem is bit similar to #429 , but I cannot solve it using the solution given in #429 so I posted this issue.

I used the script to convert a working mxnet model to tensorflow. During the conversion, there were some user warning: "You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of: data"
"Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer."

But the conversion can complete without error. And I tried to use the generated .pb file to do a single inference, it throws an error: "google.protobuf.message.DecodeError: Error parsing message" I tried the method provided in #429 , and still got an error: "AttributeError: module 'platform' has no attribute 'machine'". Seems like it is a problem with h5py, but I cannot find a solution online.

Any help is appreciated, thanks

**Comment by rainLiuplus** [comment]
Hi @WIll-Xu35 , the `.pb` file is generated by `saved_model`. Thus please use [this](https://www.tensorflow.org/guide/saved_model#loading_a_savedmodel_in_python) to load a SavedModel. Thanks!

**Comment by WIll-Xu35** [comment]
Hi @rainLiuplus , thank you for your response, I've successfully loaded the converted model.

One more question, inside the original mxnet model, the input node and output node are named 'data' and 'fc1'. In the converted TF model, I can find a single 'data' node and use it as input node. However, for the 'fc1' node, I'm a bit confused.

Inside the mxnet .json file, there are nodes named 'fc1_gamma', 'fc1_beta', 'fc1_moving_mean', 'fc1_moving_var', and finally, 'fc1'. But I only found these nodes inside the converted TF model:

fc1_mean/initial_value
fc1_mean
fc1_mean/Assign
fc1_mean/read
fc1_var/initial_value
fc1_var
fc1_var/Assign
fc1_var/read
fc1_bias/initial_value
fc1_bias
fc1_bias/Assign
fc1_bias/read
fc1/add/y
fc1/add
fc1/Rsqrt
fc1/mul
fc1/mul_1
fc1/sub
fc1/add_1

I'm a bit confused which one is the output. And why some of the layers (i.e. a fc layer named pre_fc1) is not present in the converted TF model (I cannot find a node named pre_fc1). If it is converted, how is it named, what is the convention of translating the layers' names between mxnet and TF.

I really appreciate your help.

**Comment by hxmhxm** [comment]
> Hi @rainLiuplus , thank you for your response, I've successfully loaded the converted model.
> 
> One more question, using Tensorboard, I've found the output node and I've run inference path on a single image input to do a test. But the test result is different from the original mxnet model. Will there be some precision loss during the mmdnn conversion?
> 
> Even if there is some precision loss, the result I got seems wrong. I'm wondering if the input I feed the TF model is wrong. The original mxnet model takes input of 3x112x112, while the converted TF model takes input of 112x112x3. The original input is an image in RGB order and transposed to the order of (2, 0, 1), making it 3x112x112. However, I tried to feed the TF model both RGB and BGR image of dimension 112x112x3, the result is still not close to the original mxnet model.
> 
> Do you have any idea what may have caused this?
> 
> And what is the usage of the massive 'save' node in the converted TF model?
> 
> Thank you so much for your help.

I have the same problem as you. Have you solved it yet?
